#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Print the constant tables used by karplus.c.

Run it again only if a mapping changes:
    python3 scripts/gen_tables.py > ks_tables.inc
Both tables use the phase delay at DC of a first-order allpass,
H(z) = (a + z^-1) / (1 + a z^-1), which is (1 - a) / (1 + a) samples.
"""

def frac_coef():
    # Fractional tuning allpass: delay d in [0.5, 1.5) at Q8, index d*256-128.
    out = []
    for i in range(256):
        d = (i + 128) / 256.0
        out.append(round(32768 * (1 - d) / (1 + d)))
    return out

def stiff_delay():
    # Stiffness allpass: a = -(stiff * 116) / 32768, stiff 0..127.
    out = []
    for s in range(128):
        a = -(s * 116) / 32768.0
        out.append(round(256 * (1 - a) / (1 + a)))
    return out

def dump(name, ctype, values):
    print('static const %s %s[%d] = {' % (ctype, name, len(values)))
    for i in range(0, len(values), 12):
        print('    ' + ', '.join(str(v) for v in values[i:i + 12]) + ',')
    print('};')

print('/* Generated by scripts/gen_tables.py; do not edit by hand. */')
dump('ks_frac_coef', 'int16_t', frac_coef())
dump('ks_stiff_delay_q8', 'uint16_t', stiff_delay())
