#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Convert ASCII icons into the firmware's Bitmap pixel format.

The Digitakt's blit (0x400c2960) reads bitmaps by column: one 32-bit long
per column, the top row in bit 31. A mask in the same layout selects the
pixels written. Run it again after editing an icon:
    python3 scripts/gen_icons.py > ks_icons.inc
'#' is a lit pixel, '.' an unlit one; the mask covers the whole icon so it
replaces what was under it.
"""

W, H = 15, 15

# EXC values in UI order: 0 BOW, 1 HIT, 2 NOISE, 3 PLUCK.
ICONS = {
    'bow': [  # a bow's arc and hair, crossing a string
        ".......#.......",
        ".......#.......",
        ".......#.......",
        "..###..#.......",
        ".#...###.......",
        "#......####....",
        "#......#...##..",
        "##############.",
        ".......#.......",
        ".......#.......",
        ".......#.......",
        ".......#.......",
        ".......#.......",
        ".......#.......",
        ".......#.......",
    ],
    'hit': [  # a mallet coming down on a string
        "...............",
        "..#####........",
        ".#######.......",
        ".#######.......",
        "..#####........",
        "....#..........",
        ".....#.........",
        "......#........",
        ".......#.......",
        "........#......",
        "...............",
        "###############",
        "...............",
        "...............",
        "...............",
    ],
    'noise': [  # a jagged random wave
        "...............",
        "...............",
        "...#...........",
        "...#.......#...",
        "...#.#.....#...",
        ".#.#.#.....##..",
        ".#.#.#..#..#.#.",
        "#.##.##.#.##.#.",
        "....#..#.#.#..#",
        "....#..#.#.#...",
        "....#....#.....",
        "..........#....",
        "...............",
        "...............",
        "...............",
    ],
    'pluck': [  # a string pulled aside by a pick
        "...............",
        "...............",
        "......###......",
        ".......#.......",
        ".......#.......",
        "......#.#......",
        ".....#...#.....",
        "....#.....#....",
        "...#.......#...",
        "..#.........#..",
        ".#...........#.",
        "#.............#",
        "...............",
        "...............",
        "...............",
    ],
}


def columns(rows):
    assert len(rows) == H and all(len(r) == W for r in rows), rows
    out = []
    for x in range(W):
        v = 0
        for y in range(H):
            if rows[y][x] == '#':
                v |= 1 << (31 - y)
        out.append(v)
    return out


def dump(name, values):
    print('static const uint32_t %s[%d] = {' % (name, len(values)))
    for i in range(0, len(values), 4):
        print('    ' + ', '.join('0x%08x' % v for v in values[i:i + 4]) + ',')
    print('};')


print('/* Generated by scripts/gen_icons.py; do not edit by hand. */')
print('#define KS_ICON_W %d' % W)
print('#define KS_ICON_H %d' % H)
for name in ('bow', 'hit', 'noise', 'pluck'):
    dump('ks_icon_' + name, columns(ICONS[name]))
full = (0xffffffff << (32 - H)) & 0xffffffff
dump('ks_icon_mask', [full] * W)
