#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Print the constant tables used by karplus.c.

DECAY's tables follow the String model of Mutable Instruments Rings
(Emilie Gillet, MIT): a T60 in seconds, so the decay time does not depend
on the note.

Run it again only if a mapping changes:
    python3 scripts/gen_tables.py > ks_tables.inc
Both tables use the phase delay at DC of a first-order allpass,
H(z) = (a + z^-1) / (1 + a z^-1), which is (1 - a) / (1 + a) samples.
"""

import math


def frac_coef():
    # Fractional tuning allpass: delay d in [0.5, 1.5) at Q8, index d*256-128.
    out = []
    for i in range(256):
        d = (i + 128) / 256.0
        out.append(round(32768 * (1 - d) / (1 + d)))
    return out

def stiff_delay():
    # Stiffness allpass: a = -(stiff * 116) / 32768, stiff 0..127.
    out = []
    for s in range(128):
        a = -(s * 116) / 32768.0
        out.append(round(256 * (1 - a) / (1 + a)))
    return out

def decay_rt60():
    # DECAY 0..127 to a T60 in 48 kHz samples, Rings' curve:
    # x = d * (2 - d), T60 = 0.07 s * 2^(8 x), d = DECAY / 127.
    out = []
    for v in range(128):
        d = v / 127.0
        x = d * (2 - d)
        out.append(round(0.07 * 2 ** (8 * x) * 48000))
    return out

def exp2_neg():
    # 2^(-i/64) for i = 0..64, Q16 (the first entry is exactly 65536).
    return [round(65536 * 2 ** (-i / 64.0)) for i in range(65)]

def infinite_weights():
    # DECAY 121..127 crossfade the loop gain towards 1.0, Q8, as Rings does
    # above 95% of its damping control.
    return [round(256 * (v - 120) / 7.0) for v in range(121, 128)]

def onepole_k():
    # TONE's loop lowpass: k = 1 - e^(-2 pi x), x = cutoff / sample rate,
    # for x = i / 256, i = 0..128 (up to half the sample rate), Q15.
    return [min(32767, round(32768 * (1 - math.exp(-2 * math.pi * i / 256.0))))
            for i in range(129)]

def decay_cutoff():
    # Rings raises the damping filter's cutoff with the decay time:
    # + 48 * d^2 semitones above the note, d = DECAY / 127, Q8.
    return [round(256 * 48 * (v / 127.0) ** 2) for v in range(128)]

def dump(name, ctype, values):
    print('static const %s %s[%d] = {' % (ctype, name, len(values)))
    for i in range(0, len(values), 12):
        print('    ' + ', '.join(str(v) for v in values[i:i + 12]) + ',')
    print('};')

print('/* Generated by scripts/gen_tables.py; do not edit by hand. */')
dump('ks_frac_coef', 'int16_t', frac_coef())
dump('ks_stiff_delay_q8', 'uint16_t', stiff_delay())
dump('ks_decay_rt60', 'uint32_t', decay_rt60())
dump('ks_exp2_neg_q16', 'uint32_t', exp2_neg())
dump('ks_decay_infinite_q8', 'uint16_t', infinite_weights())
dump('ks_onepole_k', 'uint16_t', onepole_k())
dump('ks_decay_cutoff_q8', 'uint16_t', decay_cutoff())
